name: Laravel 9 Lint & Static Analysis

on:
  push:
    branches:
      - main
      - develop
      - master
  pull_request:
    branches:
      - main
      - develop
      - master

jobs:
  laravel-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP 8.2.13
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.13'
          tools: composer
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run PHP CodeSniffer
        run: |
          ./vendor/bin/phpcs --standard=PSR12 app/ routes/ tests/

      - name: Run PHP CS Fixer
        run: |
          ./vendor/bin/php-cs-fixer fix app/ routes/ tests/ --dry-run --diff


      - name: Run Larastan (PHPStan)
        run: |
          ./vendor/bin/phpstan analyse app/ --level max
